DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (
DOMICILIO_ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL,
PROVINCIA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
PACIENTE_ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DNI INT NOT NULL,
FECHA_INGRESO DATE NOT NULL,
PACIENTE_DOMICILIO_ID INT NOT NULL);

INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES
 ('Loma Los Bernal',5,'Campo','Alizares');
 INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES
  ('Poblado',3,'Unidad','Condado');
INSERT INTO PACIENTES (APELLIDO, NOMBRE, EMAIL, DNI, FECHA_INGRESO, PACIENTE_DOMICILIO_ID) VALUES
 ('Rivera','Jairo','jairorive@yahoo.com',99854,'1994-07-29',1);
 INSERT INTO PACIENTES (APELLIDO, NOMBRE, EMAIL, DNI, FECHA_INGRESO, PACIENTE_DOMICILIO_ID) VALUES
  ('Lopez','Maria','marialo@yahoo.com',12587,'1954-03-29',2);

DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (
ODONTOLOGO_ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
MATRICULA INT NOT NULL);

INSERT INTO ODONTOLOGOS (APELLIDO, NOMBRE, MATRICULA) VALUES
('Hernandez','Ricardo',9852);

INSERT INTO ODONTOLOGOS (APELLIDO, NOMBRE, MATRICULA) VALUES
('Miraflores','Miranda',1265);

DROP TABLE IF EXISTS TURNOS;
CREATE TABLE TURNOS (
    TURNO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PACIENTE_ID INT,
    ODONTOLOGO_ID INT,
    FECHA DATE
);

INSERT INTO TURNOS (PACIENTE_ID, ODONTOLOGO_ID, FECHA)
    VALUES (1, 2, '2022-02-15');
INSERT INTO TURNOS (PACIENTE_ID, ODONTOLOGO_ID, FECHA)
    VALUES (1, 1, '2022-03-08');
INSERT INTO TURNOS (PACIENTE_ID, ODONTOLOGO_ID, FECHA)
    VALUES (2, 1, '2022-04-26');