-- MySQL Script generated by MySQL Workbench
-- Mon Feb 21 13:03:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema playground
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema playground
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `playground` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `playground` ;

-- -----------------------------------------------------
-- Table `playground`.`carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `playground`.`carrera` ;

CREATE TABLE IF NOT EXISTS `playground`.`carrera` (
  `idCarrera` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `playground`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `playground`.`categorias` ;

CREATE TABLE IF NOT EXISTS `playground`.`categorias` (
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `playground`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `playground`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `playground`.`usuarios` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `FKcategoria_idx` (`categoria` ASC) VISIBLE,
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `playground`.`categorias` (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `playground`.`usuarios_carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `playground`.`usuarios_carrera` ;

CREATE TABLE IF NOT EXISTS `playground`.`usuarios_carrera` (
  `id` INT NOT NULL,
  `usuario` INT NOT NULL,
  `carrera` INT NOT NULL,
  `fechainscripcion` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`usuario` ASC) INVISIBLE,
  INDEX `carrera_idx` (`carrera` ASC) VISIBLE,
  CONSTRAINT `carrera`
    FOREIGN KEY (`carrera`)
    REFERENCES `playground`.`carrera` (`idCarrera`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `playground`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
