DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(200) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL,
PROVINCIA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(45) NOT NULL,
  DNI INT NOT NULL,
  FECHA_INGRESO DATE NOT NULL,
  DOMICILIO_ID INT NOT NULL,
  INDEX `DOMICILIO_ID_idx` (`domicilio_id` ASC) VISIBLE,
  CONSTRAINT `DOMICILIO_ID`
    FOREIGN KEY (`DOMICILIO_ID`)
    REFERENCES `domicilio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);